### PR TITLE
Update and pin `mypy` and add CI

### PR DESCRIPTION
**Pull request by rchl**
Adding Sublime's Text own Python `Lib` directory broke mypy with an error like:

```
/Applications/Sublime Text.app/Contents/MacOS/Lib/python33 is in the MYPYPATH. Please remove it.
See https://mypy.readthedocs.io/en/stable/running_mypy.html#how-mypy-handles-imports for more info
```

Instead of including ST's Lib directory, bundle ST stubs.

### CODE REVIEW

**Comment by rchl** [comment]
To be fair I don't really understand why old approach broke mypy.
In theory these days would be better to use ST's own files as that would be always up to date and those include types these days...

**Comment by rchl** [comment]
Looked at mypy's code a bit more and I think I understand it now.

Mypy doesn't like when path in `MYPYPATH` is already included in `PYTHONPATH`. I need the path in `PYTHONPATH` so that Jedi can analyze types so the solution in theory is to only add paths to `PYTHONPATH`. And that sort of works, Mypy can see the types too but then it complains about another type-related thing:

Screenshot 2022-09-16 at 21 56 04

**Comment by rchl** [comment]
The initial error is still there with those changes because the paths are still duplicated...

This is so stupid, mypy shouldn't be complaining about that...

**Comment by rchl** [comment]
Seems like the whole issue is just a regression in `mypy`...
https://github.com/python/mypy/issues/7604#issuecomment-1249824784

**Comment by predragnikolic** [comment]
Will we close this PR because this is a regression in mypy?

**Comment by rchl** [comment]
But I guess I will not go with bundling external types if I don't have to.

**Pull request merged**
